### ISSUE TITLE
Mod just not working 

### ISSUE THREAD

**Issue by utade** [Simiea/simple-portal-gun#1]
Have the mod installed and no added categories for the items/no items , the mod is here but it does nothing
![image](https://github.com/Simiea/simple-portal-gun/assets/105519787/85d5b0a8-68ad-4cbd-90eb-0dd65757cc42)
![image](https://github.com/Simiea/simple-portal-gun/assets/105519787/c9f7e2d3-2632-4717-a950-c11333a4bc46)

**Comment by Simiea** [comment]
If you go to the gallery on the modrinth page you can see the crafting recipe if you are in survival. If you want this item for creative mode, run this command
`/function portal_gun:craft_portal_gun`
